'use client';

import { useState, useEffect } from 'react';
import { X, Download, FileText, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { format } from 'date-fns';

export interface CaseBrief {
    title: string;
    client_goal: string;
    parties: { name: string; role: string }[];
    chronology: { date: string; event: string }[];
    legal_issues: string[];
    applicable_laws: { law: string; section: string }[];
    evidence_checklist: { item: string; status: 'available' | 'missing' | 'unknown'; description: string }[];
    immediate_actions: string[];
    missing_info: string[];
}

interface CaseBriefModalProps {
    brief: CaseBrief | null;
    isLoading: boolean;
    onClose: () => void;
    onGenerate?: () => void;
}

export function CaseBriefModal({ brief, isLoading, onClose, onGenerate }: CaseBriefModalProps) {
    useEffect(() => {
        // Auto-generate if brief is missing and not loading
        if (!brief && !isLoading && onGenerate) {
            onGenerate();
        }
    }, []); // Run once on mount

    const handlePrint = () => {
        window.print();
    };

    return (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-sm print:p-0 print:bg-white print:static">
            <div className="bg-white w-full max-w-4xl h-[90vh] rounded-2xl shadow-2xl flex flex-col print:h-auto print:shadow-none print:w-full print:max-w-none animate-in fade-in zoom-in-95 duration-200">

                {/* Header - Hidden in Print */}
                <div className="flex items-center justify-between p-6 border-b border-slate-100 print:hidden flex-shrink-0">
                    <div className="flex items-center gap-3">
                        <div className="w-12 h-12 bg-blue-100 rounded-xl flex items-center justify-center text-blue-600">
                            <FileText className="w-6 h-6" />
                        </div>
                        <div>
                            <h2 className="text-xl font-bold text-slate-900">Case Brief Generator</h2>
                            <p className="text-sm text-slate-500">AI-Structured Case File • Ready for Lawyer Review</p>
                        </div>
                    </div>
                    <div className="flex items-center gap-2">
                        <Button variant="default" onClick={handlePrint} disabled={!brief || isLoading} className="gap-2 bg-blue-600 hover:bg-blue-700">
                            <Download className="w-4 h-4" />
                            Download PDF
                        </Button>
                        <Button variant="ghost" size="icon" onClick={onClose} className="rounded-full">
                            <X className="w-5 h-5" />
                        </Button>
                    </div>
                </div>

                {/* Content */}
                <div className="flex-1 overflow-y-auto p-8 print:overflow-visible print:p-0 bg-slate-50/50">
                    {isLoading ? (
                        <div className="h-full flex flex-col items-center justify-center text-slate-400 space-y-6">
                            <div className="relative">
                                <div className="w-16 h-16 border-4 border-slate-200 border-t-blue-600 rounded-full animate-spin" />
                                <FileText className="w-6 h-6 text-slate-400 absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2" />
                            </div>
                            <div className="text-center max-w-sm">
                                <p className="text-xl font-bold text-slate-900 mb-2">Structuring Case File...</p>
                                <p className="text-slate-500">Our Legal AI is analyzing your conversation history to extract parties, dates, and legal issues.</p>
                            </div>
                        </div>
                    ) : brief ? (
                        <div className="max-w-3xl mx-auto bg-white shadow-sm border border-slate-200 p-10 min-h-full print:shadow-none print:border-none print:p-0">

                            {/* Report Header */}
                            <div className="text-center border-b-2 border-slate-900 pb-6 mb-8">
                                <h1 className="text-3xl font-bold text-slate-900 mb-2 uppercase tracking-wide font-serif">Privileged Case Brief</h1>
                                <p className="text-slate-600 italic font-serif">Generated by JusticeAI • {format(new Date(), 'PPP')}</p>
                            </div>

                            <div className="space-y-8 font-serif">
                                {/* 1. Case Metadata */}
                                <div className="bg-slate-50 p-6 rounded-lg border border-slate-200 print:bg-transparent print:border-none print:p-0">
                                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                                        <div>
                                            <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-1 font-sans">Case Title</h3>
                                            <p className="text-xl font-semibold text-slate-900">{brief.title}</p>
                                        </div>
                                        <div>
                                            <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-1 font-sans">Client Goal</h3>
                                            <p className="text-lg text-slate-800">{brief.client_goal}</p>
                                        </div>
                                    </div>
                                </div>

                                {/* 2. Parties */}
                                <section>
                                    <h3 className="text-lg font-bold text-slate-900 border-b border-slate-200 pb-2 mb-4 font-sans uppercase">I. Parties Involved</h3>
                                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                                        {brief.parties.map((p, i) => (
                                            <div key={i} className="flex justify-between items-center p-3 border rounded bg-white print:border-slate-300">
                                                <span className="font-semibold text-slate-900">{p.role}</span>
                                                <span className="text-slate-600">{p.name}</span>
                                            </div>
                                        ))}
                                    </div>
                                </section>

                                {/* 3. Chronology */}
                                <section>
                                    <h3 className="text-lg font-bold text-slate-900 border-b border-slate-200 pb-2 mb-4 font-sans uppercase">II. Chronology of Events</h3>
                                    <div className="space-y-4 text-sm">
                                        {brief.chronology.map((event, i) => (
                                            <div key={i} className="flex gap-4">
                                                <div className="w-24 flex-shrink-0 font-bold text-slate-500 text-right pt-1">{event.date}</div>
                                                <div className="flex-1 pb-4 border-l-2 border-slate-200 pl-4 relative">
                                                    <div className="absolute -left-[5px] top-1.5 w-2 h-2 rounded-full bg-slate-400 print:bg-slate-800" />
                                                    <p className="text-slate-900">{event.event}</p>
                                                </div>
                                            </div>
                                        ))}
                                    </div>
                                </section>

                                {/* 4. Legal Analysis */}
                                <section>
                                    <h3 className="text-lg font-bold text-slate-900 border-b border-slate-200 pb-2 mb-4 font-sans uppercase">III. Legal Analysis</h3>
                                    <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                                        <div>
                                            <h4 className="font-bold text-slate-700 mb-2 font-sans text-sm uppercase">Key Legal Issues</h4>
                                            <ul className="list-disc list-inside space-y-1 text-slate-800">
                                                {brief.legal_issues.map((issue, i) => <li key={i}>{issue}</li>)}
                                            </ul>
                                        </div>
                                        <div>
                                            <h4 className="font-bold text-slate-700 mb-2 font-sans text-sm uppercase">Applicable Laws</h4>
                                            <ul className="space-y-2">
                                                {brief.applicable_laws.map((law, i) => (
                                                    <li key={i} className="text-slate-800 bg-blue-50 px-3 py-1.5 rounded inline-block mr-2 mb-1 print:bg-transparent print:p-0 print:border print:border-slate-200">
                                                        <span className="font-bold">{law.law}</span> <span className="text-slate-500 block text-xs">Section {law.section}</span>
                                                    </li>
                                                ))}
                                            </ul>
                                        </div>
                                    </div>
                                </section>

                                {/* 5. Action Plan */}
                                <section className="break-inside-avoid">
                                    <h3 className="text-lg font-bold text-slate-900 border-b border-slate-200 pb-2 mb-4 font-sans uppercase">IV. Strategic Plan</h3>

                                    {brief.missing_info.length > 0 && (
                                        <div className="mb-6 bg-amber-50 p-4 rounded border border-amber-100 print:bg-transparent print:border print:border-amber-200">
                                            <h4 className="font-bold text-amber-800 mb-2 flex items-center gap-2 font-sans text-sm uppercase">
                                                <span className="">⚠</span> Missing Critical Information
                                            </h4>
                                            <ul className="list-disc list-inside text-slate-800">
                                                {brief.missing_info.map((info, i) => <li key={i}>{info}</li>)}
                                            </ul>
                                        </div>
                                    )}

                                    <div className="mb-6">
                                        <h4 className="font-bold text-slate-700 mb-3 font-sans text-sm uppercase">Evidence & Documentation</h4>
                                        <div className="space-y-3">
                                            {brief.evidence_checklist.map((item, i) => (
                                                <div key={i} className="flex gap-4 p-3 border border-slate-200 rounded-lg bg-white print:border-slate-300 break-inside-avoid">
                                                    <div className={`flex-shrink-0 w-24 flex flex-col items-center justify-center rounded border text-xs font-bold uppercase tracking-wider h-full min-h-[3rem] ${item.status === 'available' ? 'bg-green-50 text-green-700 border-green-100' :
                                                            item.status === 'missing' ? 'bg-red-50 text-red-700 border-red-100' :
                                                                'bg-amber-50 text-amber-700 border-amber-100'
                                                        }`}>
                                                        {item.status}
                                                    </div>
                                                    <div className="flex-1">
                                                        <p className="font-bold text-slate-900">{item.item}</p>
                                                        <p className="text-sm text-slate-600">{item.description}</p>
                                                    </div>
                                                </div>
                                            ))}
                                        </div>
                                    </div>

                                    <div>
                                        <h4 className="font-bold text-slate-700 mb-3 font-sans text-sm uppercase">Immediate Actions</h4>
                                        <ol className="list-decimal list-inside space-y-2 font-medium text-slate-900 bg-slate-50 p-4 rounded print:bg-transparent print:p-0">
                                            {brief.immediate_actions.map((action, i) => <li key={i}>{action}</li>)}
                                        </ol>
                                    </div>
                                </section>
                            </div>

                            {/* Footer */}
                            <div className="mt-12 pt-6 border-t border-slate-200 text-center text-xs text-slate-400 print:fixed print:bottom-4 print:left-0 print:w-full font-sans">
                                Generated by JusticeAI • Privileged & Confidential Work Product • Not Legal Advice
                            </div>

                        </div>
                    ) : (
                        <div className="flex flex-col items-center justify-center h-64 text-red-500">
                            <AlertCircle className="w-10 h-10 mb-2" />
                            <p className="font-medium">Failed to generate case brief. Please try again.</p>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
}

function AlertCircle({ className }: { className?: string }) {
    return (
        <svg
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
            className={className}
        >
            <circle cx="12" cy="12" r="10" />
            <line x1="12" y1="8" x2="12" y2="12" />
            <line x1="12" y1="16" x2="12.01" y2="16" />
        </svg>
    );
}
